#!/usr/bin/env node
/**
 * Generates site/assets/site-config.js for a given site from config/<site>.json.
 * The frontend reads window.SITE_CONFIG at boot — this is the ONLY per-site
 * artifact in the otherwise identical frontend bundle.
 *
 * Usage: node scripts/build_site_config.js <core|watch> [outFile]
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.join(__dirname, '..');

const site = process.argv[2];
if (!site || !/^[a-z0-9_-]+$/.test(site)) {
  console.error('Usage: node scripts/build_site_config.js <core|watch> [outFile]');
  process.exit(1);
}

const cfgPath = path.join(ROOT_DIR, 'config', `${site}.json`);
const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));

// Only the frontend-relevant subset is exposed to the browser.
const siteConfig = {
  siteId: cfg.site_id,
  siteName: cfg.site_name,
  pageTitle: cfg.page_title,
  dataBase: cfg.data_base,
  analyticsToken: cfg.analytics_token,
  tradersColumnLabel: cfg.traders_column_label,
  githubUrl: cfg.github_url,
  polymarketReferral: cfg.polymarket_referral,
  inactivityTimeoutMinutes: cfg.inactivity_timeout_minutes,
  autoReloadSeconds: cfg.auto_reload_seconds,
};

const out = process.argv[3] || path.join(ROOT_DIR, 'site', 'assets', 'site-config.js');
fs.writeFileSync(out, `// Generated by scripts/build_site_config.js — do not edit by hand.\nwindow.SITE_CONFIG = ${JSON.stringify(siteConfig, null, 2)};\n`, 'utf-8');
console.log(`Wrote ${out} for site "${site}"`);
